##
##  Makefile -- Build procedure for sample vim Apache module
##  Autogenerated via ``apxs -n vim -g''.
##

builddir=.
top_srcdir=/usr
top_builddir=/usr
include /usr/share/httpd/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
DEFS=-DUSE_ICONV -DUSE_X11
#DEFS=-Dmy_define=my_value
INCLUDES=$(shell pkg-config --cflags x11 apr-json-0)
LIBS=$(shell pkg-config --libs x11 apr-json-0)

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f *.o *.lo *.slo *.la

#   simple test
test: reload
	lynx -mime_header http://localhost/vim

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

